# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'El Taquillero' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for El Taquillero

pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/Firestore'

  target 'El TaquilleroTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'El TaquilleroUITests' do
    # Pods for testing
  end

end
